In [1]:
import numpy as np
import pandas as pd

In [5]:
l = [1,2,3]

labels = 'A B C'.split()

In [6]:
narr = np.array(l)

In [7]:
narr

array([1, 2, 3])

In [8]:
labels

['A', 'B', 'C']

In [11]:
s1 = pd.Series(data = l, index = labels)

In [12]:
s1

A    1
B    2
C    3
dtype: int64

In [13]:
s1 = pd.Series(data=labels, index=l)

In [14]:
s1

1    A
2    B
3    C
dtype: object

In [15]:
s1 = pd.Series(data=l)

In [16]:
s1

0    1
1    2
2    3
dtype: int64

In [17]:
d = {'usa':2, "Inda":3, "russia":5}

In [18]:
d2 = {"usa":3,"japan":8,"russia":4}

In [19]:
c1 = pd.Series(d)
c2 = pd.Series(d2)

In [35]:
type(c1)

pandas.core.series.Series

In [21]:
c2

usa       3
japan     8
russia    4
dtype: int64

In [22]:
c1+c2

Inda      NaN
japan     NaN
russia    9.0
usa       5.0
dtype: float64

In [25]:
narr = np.random.rand(5,4)

In [26]:
narr

array([[0.76510699, 0.65545181, 0.55611078, 0.3144722 ],
       [0.56889067, 0.70849905, 0.54331749, 0.79523807],
       [0.41150794, 0.37237527, 0.27692625, 0.35119903],
       [0.90690569, 0.36694128, 0.41638131, 0.5062639 ],
       [0.47781914, 0.47083668, 0.45812306, 0.2326708 ]])

In [27]:
col_list = 'W X Y Z'.split()
row_list = 'A B C D E'.split()

In [28]:
col_list

['W', 'X', 'Y', 'Z']

In [29]:
row_list

['A', 'B', 'C', 'D', 'E']

In [30]:
df = pd.DataFrame(data=narr, index=row_list, columns=col_list)

In [31]:
df

W         X         Y         Z
A  0.765107  0.655452  0.556111  0.314472
B  0.568891  0.708499  0.543317  0.795238
C  0.411508  0.372375  0.276926  0.351199
D  0.906906  0.366941  0.416381  0.506264
E  0.477819  0.470837  0.458123  0.232671

In [47]:
df[['W', 'X']]

W         X
A  0.765107  0.655452
B  0.568891  0.708499
C  0.411508  0.372375
D  0.906906  0.366941
E  0.477819  0.470837

In [51]:
df.loc[['A']]

pandas.core.frame.DataFrame

In [53]:
df.iloc[[0]]

W         X         Y         Z
A  0.765107  0.655452  0.556111  0.314472

In [54]:
df.loc[['A', 'B']][['X', 'Y']]

X         Y
A  0.655452  0.556111
B  0.708499  0.543317

In [55]:
df.loc[['A','B'], ['X', 'Y']]

X         Y
A  0.655452  0.556111
B  0.708499  0.543317

In [56]:
df.iloc[2:4, 1:3]

X         Y
C  0.372375  0.276926
D  0.366941  0.416381

In [61]:
df['NEW'] = df['X'] + df['Y']

In [62]:
df

W         X         Y         Z       NEW
A  0.765107  0.655452  0.556111  0.314472  1.211563
B  0.568891  0.708499  0.543317  0.795238  1.251817
C  0.411508  0.372375  0.276926  0.351199  0.649302
D  0.906906  0.366941  0.416381  0.506264  0.783323
E  0.477819  0.470837  0.458123  0.232671  0.928960

In [63]:
df.drop('NEW', axis=1)

W         X         Y         Z
A  0.765107  0.655452  0.556111  0.314472
B  0.568891  0.708499  0.543317  0.795238
C  0.411508  0.372375  0.276926  0.351199
D  0.906906  0.366941  0.416381  0.506264
E  0.477819  0.470837  0.458123  0.232671

In [64]:
df

W         X         Y         Z       NEW
A  0.765107  0.655452  0.556111  0.314472  1.211563
B  0.568891  0.708499  0.543317  0.795238  1.251817
C  0.411508  0.372375  0.276926  0.351199  0.649302
D  0.906906  0.366941  0.416381  0.506264  0.783323
E  0.477819  0.470837  0.458123  0.232671  0.928960

In [65]:
df.drop('NEW', axis=1, inplace=True)

In [66]:
df

W         X         Y         Z
A  0.765107  0.655452  0.556111  0.314472
B  0.568891  0.708499  0.543317  0.795238
C  0.411508  0.372375  0.276926  0.351199
D  0.906906  0.366941  0.416381  0.506264
E  0.477819  0.470837  0.458123  0.232671

In [67]:
l = 'ny ca ab il tx'.split()

In [68]:
df['states'] = l

In [69]:
df

W         X         Y         Z states
A  0.765107  0.655452  0.556111  0.314472     ny
B  0.568891  0.708499  0.543317  0.795238     ca
C  0.411508  0.372375  0.276926  0.351199     ab
D  0.906906  0.366941  0.416381  0.506264     il
E  0.477819  0.470837  0.458123  0.232671     tx

In [70]:
df.reset_index(inplace=True)

In [71]:
df

index         W         X         Y         Z states
0     A  0.765107  0.655452  0.556111  0.314472     ny
1     B  0.568891  0.708499  0.543317  0.795238     ca
2     C  0.411508  0.372375  0.276926  0.351199     ab
3     D  0.906906  0.366941  0.416381  0.506264     il
4     E  0.477819  0.470837  0.458123  0.232671     tx

In [75]:
df.set_index('states', inplace=True)

In [82]:
df

index         W         X         Y         Z
states                                              
ny         A  0.765107  0.655452  0.556111  0.314472
ca         B  0.568891  0.708499  0.543317  0.795238
ab         C  0.411508  0.372375  0.276926  0.351199
il         D  0.906906  0.366941  0.416381  0.506264
tx         E  0.477819  0.470837  0.458123  0.232671

In [89]:
df.loc[['ny', 'il']]

index         W         X         Y         Z
states                                              
ny         A  0.765107  0.655452  0.556111  0.314472
il         D  0.906906  0.366941  0.416381  0.506264

In [90]:
df['index']

states
ny    A
ca    B
ab    C
il    D
tx    E
Name: index, dtype: object

In [94]:
df.columns = ['old_index', 'W', 'X', 'Y', 'Z']

In [95]:
df

old_index         W         X         Y         Z
states                                                  
ny             A  0.765107  0.655452  0.556111  0.314472
ca             B  0.568891  0.708499  0.543317  0.795238
ab             C  0.411508  0.372375  0.276926  0.351199
il             D  0.906906  0.366941  0.416381  0.506264
tx             E  0.477819  0.470837  0.458123  0.232671

In [97]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, ny to tx
Data columns (total 5 columns):
old_index    5 non-null object
W            5 non-null float64
X            5 non-null float64
Y            5 non-null float64
Z            5 non-null float64
dtypes: float64(4), object(1)
memory usage: 400.0+ bytes


In [98]:
d = {"company":"goog goog msft mst fb fb".split(), "salesperson":"a b c d e f".split(), "sales":[100,300,405,32,233,564], "profit":[987,345,221,456,765,321]}

In [99]:
d

{'company': ['goog', 'goog', 'msft', 'mst', 'fb', 'fb'],
 'salesperson': ['a', 'b', 'c', 'd', 'e', 'f'],
 'sales': [100, 300, 405, 32, 233, 564],
 'profit': [987, 345, 221, 456, 765, 321]}

In [100]:
dff = pd.DataFrame(d)

In [101]:
dff

company salesperson  sales  profit
0    goog           a    100     987
1    goog           b    300     345
2    msft           c    405     221
3     mst           d     32     456
4      fb           e    233     765
5      fb           f    564     321

In [104]:
dff.groupby('company').sum()

sales  profit
company               
fb         797    1086
goog       400    1332
msft       405     221
mst         32     456

In [105]:
d1 = {"col1":[1,2, np.nan, np.nan],"col2":[444,222,444,333],"col3":[np.nan, np.nan,3,4]}

In [106]:
d1

{'col1': [1, 2, nan, nan],
 'col2': [444, 222, 444, 333],
 'col3': [nan, nan, 3, 4]}

In [107]:
ddf = pd.DataFrame(d1)

In [114]:
ddf

col1  col2  col3
0   1.0   444   NaN
1   2.0   222   NaN
2   NaN   444   3.0
3   NaN   333   4.0

In [111]:
ddf.fillna("Empty Values")

col1  col2          col3
0             1   444  Empty Values
1             2   222  Empty Values
2  Empty Values   444             3
3  Empty Values   333             4

In [117]:
ddf['col1'].fillna(ddf['col1'].mean(), inplace=True)

In [118]:
ddf

col1  col2  col3
0   1.0   444   NaN
1   2.0   222   NaN
2   1.5   444   3.0
3   1.5   333   4.0

In [119]:
ddf['col2'].unique()

array([444, 222, 333], dtype=int64)

In [120]:
ddf['col2'].nunique()

3

In [121]:
ddf['col2'].value_counts()

444    2
222    1
333    1
Name: col2, dtype: int64