In [2]:
import numpy as np

In [3]:
l = list(range(1, 11))

In [4]:
l

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [6]:
n1 = np.array(l)

In [7]:
n1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
l = [[1,2,3],[4,5,6],[7,8,9]]

In [9]:
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [10]:
n2 = np.array(l)

In [11]:
n2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
n3 = np.arange(1,11)

In [13]:
n3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
n4 = np.eye(3)

In [15]:
n4

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [16]:
n5 = np.ones(10)

In [17]:
n5

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [18]:
n6 = np.zeros(5)

In [19]:
n6

array([0., 0., 0., 0., 0.])

In [22]:
n7 = np.linspace(1,100,5)

In [23]:
n7

array([  1.  ,  25.75,  50.5 ,  75.25, 100.  ])

In [24]:
n8 = np.random.randint(1,100,10)

In [25]:
n8

array([14, 63,  6,  6, 29, 29, 15, 10, 89, 42])

In [27]:
type(n8[9])

numpy.int32

In [43]:
n = 14
type(n)

int

In [44]:
n == n8[0]

True

In [39]:
n9 = np.random.rand(3,5)

In [40]:
n9

array([[0.62542057, 0.36191685, 0.94295563, 0.53887779, 0.89542644],
       [0.49038818, 0.02449856, 0.57991518, 0.46465737, 0.11001914],
       [0.69587467, 0.90566045, 0.61828773, 0.78365125, 0.32789592]])

In [42]:
type(n9[2][1])

numpy.float64

In [45]:
n10 = np.arange(1,26)

In [46]:
n10

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [48]:
n10.shape

(25,)

In [49]:
n10.reshape(1,25)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25]])

In [50]:
n10.reshape(25,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24],
       [25]])

In [53]:
n10.reshape(5,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [66]:
n11 = np.arange(1,11)

In [67]:
n11

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [63]:
n11[:3]

array([1, 2, 3])

In [64]:
n11[1:4] *= 100

In [65]:
n11

array([  1, 200, 300, 400,   5,   6,   7,   8,   9,  10])

In [68]:
n12 = n11

In [69]:
n12

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [70]:
n11[0]= 25

In [71]:
n11

array([25,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [72]:
n12

array([25,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [75]:
n13 = n11.copy()

In [76]:
n13

array([25,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [77]:
n11[0] = 1

In [78]:
n12

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [79]:
n13

array([25,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [84]:
 n12.argsort()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int64)

In [111]:
na = np.arange(1,10)

In [112]:
na = na.reshape(3,3)

In [113]:
na[1:]

array([[4, 5, 6],
       [7, 8, 9]])

In [114]:
na[:2,1:]

array([[2, 3],
       [5, 6]])

In [115]:
na

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [116]:
na[:,:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [117]:
nar = np.random.randint(1,20,10)

In [118]:
nar

array([ 7, 19, 18, 16,  9, 18, 11,  3, 16, 15])

In [123]:
a = nar[nar<10]

In [124]:
a

array([7, 9, 3])

In [125]:
n1 = np.arange(1,11)
n2 = np.arange(11,21)

In [126]:
n1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [127]:
n2

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [128]:
n1+n2

array([12, 14, 16, 18, 20, 22, 24, 26, 28, 30])